server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
      url: jdbc:mysql://192.168.208.128:3306/test?characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver